### PR TITLE
cache-component <-> nanocomponent merge@6.0.0

### PR DESCRIPTION
**Pull request by bcomnes**
Merge branch for the cache-component and nano component merge https://github.com/hypermodules/cache-component/pull/18

- [x] re-add onload
- [x] finalize lifecycle hooks
- [x] Update Docs
- [x] Rename to nanocomponent
- [x] Add upgrade guide from cache-component 5
- [x] Add upgrade guide from nanocomponent 5
- [x] Fix tests
- [x] Update examples
- [x] merge with nanocomponent and move to choo org
- [x] Fix leaflett example
- [ ] Add browser tests (https://gist.github.com/bcomnes/fa4fa3a83807b4189356699c17207a0b)
- [ ] Make examples runnable (component playground? perhaps put this off or use that thing @toddself said)
- [ ] Refine example: we could remove the ES6 example, and put it together with the constructor bind under the same heading
- [ ] Have a few 👀 look over the CI setup to make sure everything is groovy

### CODE REVIEW

**Comment by yoshuawuyts** [comment]
neato!

**Comment by bcomnes** [comment]
I'm going to release a beta to allow for easy consumption and encourage early feedback.

**Comment by bcomnes** [comment]
@yoshuawuyts I don't seem to have publish access yet on npm.  Can I get that add?

Also whats your view on beta branches?  Merged to master on beta?  Merged to master after a real release?

**Comment by yoshuawuyts** [comment]
added to npm

**Comment by yoshuawuyts** [comment]
Also, think we should just merge to master - put out a beta release (e.g.
prerelease) and once we find it stable enough, we publish a full major

**Comment by bcomnes** [comment]
Ok merging to master.  Released as 6.0.0-0.  Installable with `nanocomponent@next`

**Comment by bcomnes** [comment]
Actually lets do it tomorrow.  Going to announce in IRC and get preprefeedback.

**Comment by bcomnes** [comment]
Actually I'll just do it now.  Revert exists for a reason.

**Pull request merged**
