### PR TITLE
Store realNode reference on proxy node

### PR DESCRIPTION
**Pull request by kristoferjoseph**
Needs the other half in nanomorph#98 to land first.

Adds real node reference and test.

### CODE REVIEW

**Comment by kristoferjoseph** [comment]
Tests are failing currently. Awaiting nanomorph PR merge.

**Comment by bcomnes** [comment]
Looks good to me.  Will approve when green.

**Comment by bcomnes** [comment]
I'm going to do the same thing, and release a beta version.

**Comment by bcomnes** [comment]
🎉`nanocomponent@7.0.0-beta1`🎉

```
$ npm i nanocomponent@beta --save
```

**Pull request merged**
