### PR TITLE
7.0.0 Beta

### PR DESCRIPTION
**Pull request by bcomnes**
Beta brach

```
$ npm i nanocomponent@beta --save
```

### CODE REVIEW

**Comment by bcomnes** [comment]
🎉`nanocomponent@7.0.0-beta1`🎉
https://github.com/choojs/nanocomponent/releases/tag/v7.0.0-beta1

**Comment by kristoferjoseph** [comment]
Just found a leaked `proxy-node` in a list.
Looks like there is still a case where these are leaking
screen shot 2018-03-05 at 10 30 55 am

**Comment by bcomnes** [comment]
Haven't done a deep review of the updated nanomorph algorithm, but I think its goign to come down to really thinking through that.  

Know how to reproduce?

**Comment by bcomnes** [comment]
Closing this until someone had bandwidth to follow up.  This was inconclusive.

**Pull request closed without merging**
